version: "3.7"

services:
  redis:
    image: redis:alpine
    container_name: redis
  backend:
    build: ./back
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - redis