export const AVADA_KEDAVRA = 'AVADA_KEDAVRA';
export const ENDOLORIS = 'ENDOLORIS';
export const STUPEFIX = 'STUPEFIX';
export const DIFFINDO = "DIFFINDO";
export const SECTUM_SEMPRA = "SECTUM_SEMPRA";
export const VULNERA_SANENTUR = "VULNERA_SANENTUR";
export const BOMBARDA = "BOMBARDA";
export const PETRIFICUS_TOTALUS = "PETRIFICUS_TOTALUS";
export const EXPELLIARMUS = 'EXPELLIARMUS';
export const INCENDIO = 'INCENDIO';
export const PROTEGO = 'PROTEGO';


const cardsKeys = [AVADA_KEDAVRA, ENDOLORIS, EXPELLIARMUS, INCENDIO, PROTEGO, STUPEFIX, DIFFINDO, SECTUM_SEMPRA, VULNERA_SANENTUR, BOMBARDA, PETRIFICUS_TOTALUS] as const;

export type CardName = typeof cardsKeys[number];
