# fly.toml file generated for arcanea on 2024-02-03T11:01:21+01:00

app = "arcanea"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "cdg"
processes = []

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
